spring:
    application:
          name: api-gateway

    data: 
       redis:
        host: localhost
        port: 6379

    cloud:
          gateway:
            routes:
              - id: user-service
                uri: lb://user-service
                predicates:
                - Path=/users/**
                filters:
                - StripPrefix=1
       
                # Rate Limiter (Now Properly Bound To Bean)
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@redisRateLimiter}"
                    key-resolver: "#{@userKeyResolver}"

                # Retry First
                - name: Retry
                  args:
                    name: userServiceRetry
                    retries: 2
                    method: GET
                    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                    backoff:
                      firstBackoff: 1s
                      maxBackoff: 3s
                      factor: 2

                # Circuit Breaker Second
                - name: CircuitBreaker
                  args: 
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/user

              - id: order-service
                uri: lb://order-service              #http://localhost:8082
                predicates:
                - Path=/orders/**
                filters:
                - StripPrefix=1

                # Rate Limiter (Now Properly Bound To Bean)
                - name: RequestRateLimiter
                  args:
                      rate-limiter: "#{@redisRateLimiter}"
                      key-resolver: "#{@userKeyResolver}"

                # Circuit Breaker Only                
                - name: CircuitBreaker
                  args:
                    name: orderServiceCircuitBreaker
                    fallbackUri: forward:/fallback/order

# Resilence4j
resilience4j:
  circuitbreaker:
   configs:
     default:
       slidingWindowSize: 2
       minimumNumberOfCalls: 2 
       failureRateThreshold: 50
       waitDurationInOpenState: 10s
       permittedNumberOfCallsInHalfOpenState: 2
       automaticTransitionFromOpenToHalfOpenEnabled: true
       recordExceptions:
          - java.lang.Exception

   instances:
       userServiceCircuitBreaker:
          baseConfig: default
       orderServiceCircuitBreaker:
          baseConfig: default

  # Time Limitter
  timelimiter:
    instances: 
      userServiceCircuitBreaker:
        timeout-duration: 2s
      orderServiceCircuitBreaker:
        timeout-duration: 2s

  # Retry Config 
  retry:
     instances:  
       userServiceRetry:    
          maxAttempts: 3
          waitDuration: 500ms

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,retries,metrics
  endpoint:
    health:
      show-details: always

server:
     port: 8080

eureka:
   client:
      service-url:
        defaultZone: http://localhost:8761/eureka


   instance:
     instance-id: ${spring.application.name}:${random.value}